apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: demo-user
  labels:
    strimzi.io/cluster: demo-cluster
  namespace: kafka-demo
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
      - resource:
          type: topic
          name: demo-topic
          patternType: literal
        operation: Read
        host: '*'
      - resource:
          type: topic
          name: demo-topic
          patternType: literal
        operation: Describe
        host: '*'
      - resource:
          type: topic
          name: demo-topic
          patternType: literal
        operation: Write
        host: '*'
      - resource:
          type: topic
          name: demo-topic
          patternType: literal
        operation: Create
        host: '*'
      - resource:
          type: group
          name: kafka-demo
          patternType: literal
        operation: Read
        host: '*'
      - resource:
          type: group
          name: kafka-demo
          patternType: literal
        operation: Write
        host: '*'
      - resource:
          type: group
          name: kafka-demo
          patternType: literal
        operation: Describe
        host: '*'
      - resource:
          type: group
          name: kafka-demo
          patternType: literal
        operation: Create
        host: '*'
    type: simple
