kind: Secret
apiVersion: v1
metadata:
  name: kafka-config
  namespace: kafka
data:
  kafka.bootstrap.servers: ZGVtby1jbHVzdGVyLWthZmthLWJvb3RzdHJhcC5rYWZrYS5zdmMuY2x1c3Rlci5sb2NhbDo5MDky
type: Opaque
