kind: Secret
apiVersion: v1
metadata:
  name: kafka-config
  namespace: kafka
data:
  kafka.bootstrap.servers: ZGVtby1jbHVzdGVyLWthZmthLWJvb3RzdHJhcDo5MDky
  kafka.sasl.mechanism: U0NSQU0tU0hBLTUxMg==
  kafka.security.protocol: U0FTTF9QTEFJTlRFWFQ=
type: Opaque
